# Generated by Django 5.2.1 on 2025-05-21 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SQLDB', '0002_wasteimage_policy_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wasteimage',
            name='policy_text',
        ),
    ]
