# Generated by Django 5.2.1 on 2025-05-21 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SQLDB', '0003_remove_wasteimage_policy_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='wasteimage',
            name='chat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='SQLDB.chathistory'),
        ),
    ]
