# Generated by Django 5.2 on 2025-05-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SQLDB', '0004_wasteimage_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chathistory',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
