# Generated by Django 5.2 on 2025-05-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SQLDB', '0005_chathistory_label_chathistory_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='reward_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
